version: 2
updates:
  # Main Go module
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded separately.
      - dependency-name: "sigs.k8s.io/cluster-api"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"
  # Test Go module
  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      test-dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"
  # ETCD backup/restore module
  - package-ecosystem: "gomod"
    directory: "exp/etcdrestore/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      test-dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"
  - package-ecosystem: "gomod"
    directory: "/exp/clusterclass"
    schedule:
      interval: "daily"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded separately.
      - dependency-name: "sigs.k8s.io/cluster-api"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/build-and-release"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/build-and-release"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
