apiVersion: v1
kind: Secret
metadata:
  name: cluster-identity-secret
type: Opaque
stringData:
  clientSecret: <>your-client-secret<>
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
spec:
  allowedNamespaces: {}
  clientID: <>your-client-id<>
  tenantID: <>your-tenant-id<>
  type: ServicePrincipal
  clientSecret:
    name: cluster-identity-secret
    namespace: default