namespace: "{{ .Values.rancherTurtles.namespace }}"
images:
- name: controller
  newName: "{{ .Values.rancherTurtles.image }}"
  newTag: "{{ .Values.rancherTurtles.imageVersion }}"
namePrefix: rancher-turtles-
resources:
- ../rbac
- ../crd
