name: Run nightly e2e tests

on:
  schedule:
    - cron: "0 0 1/2 * *"
  workflow_dispatch:

concurrency: ci_e2e_tests

jobs:
  e2e_etcd_snapshot_restore:
    uses: ./.github/workflows/run-e2e-suite.yaml
    with:
      test_suite: test/e2e/suites/etcd-snapshot-restore
      test_name: Etcd snapshot restore
      run_azure_janitor: false
      artifact_name: artifacts_etcd_snapshot_restore
      MANAGEMENT_CLUSTER_ENVIRONMENT: eks
    secrets: inherit
