name: Run nightly e2e tests

on:
  # schedule:
  #   - cron: "0 0 1/2 * *"
  workflow_dispatch:

jobs:
  e2e_import_gitops_v3:
    uses: ./.github/workflows/run-e2e-suite.yaml
    with:
      test_suite: test/e2e/suites/import-gitops-v3
      test_name: Import via GitOps [v3]
      run_azure_janitor: true
      artifact_name: artifacts_import_gitops_v3
      MANAGEMENT_CLUSTER_ENVIRONMENT: kind
    secrets: inherit
  e2e_v2prov:
    uses: ./.github/workflows/run-e2e-suite.yaml
    with:
      test_suite: test/e2e/suites/v2prov
      test_name: v2 provisioning
      run_azure_janitor: false
      artifact_name: artifacts_v2prov
      MANAGEMENT_CLUSTER_ENVIRONMENT: kind
    secrets: inherit
  e2e_update_labels:
    uses: ./.github/workflows/run-e2e-suite.yaml
    with:
      test_suite: test/e2e/suites/update-labels
      test_name: Update labels
      run_azure_janitor: false
      artifact_name: artifacts_update_labels
      MANAGEMENT_CLUSTER_ENVIRONMENT: kind
    secrets: inherit

