name: Test release process nightly

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight (UTC)
  workflow_dispatch: # Allow running manually on demand

env:
  RELEASE_TAG: v9.9.9-nightly
  GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  nightly-test-release:
    name: Tag current version for testing
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
      - name: Create fake release tag (local only)
        run: |
          git tag ${{ env.RELEASE_TAG }}

  build-push-services:
    name: Build, sign and provenance
    needs: [nightly-test-release]
    permissions:
      actions: read
      contents: write
      packages: write
      id-token: write
    strategy:
      matrix:
        destination: [ghcr]
        include:
        - destination: ghcr
          registry: ghcr.io
          username: ${{ github.actor }}
          password: GITHUB_TOKEN
          image: GHCR_IMAGE
          tag: v9.9.9-nightly
          secret_registry: false
    uses: ./.github/workflows/release.yml
    with:
      password: ${{ matrix.password }}
      username: ${{ matrix.username }}
      registry: ${{ matrix.registry }}
      tag: ${{ matrix.tag }}
      image: ${{ matrix.image }}
      secret_registry: ${{ matrix.secret_registry }}
    secrets: inherit

  release:
    name: Create helm release
    needs: [build-push-services]
    runs-on: ubuntu-latest
    env:
      PROD_REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}
      PROD_ORG: rancher
      RELEASE_DIR: .cr-release-packages
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
      - name: setupGo
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: go.mod
      - name: Package operator chart
        run: RELEASE_TAG=${{ env.RELEASE_TAG }} CHART_PACKAGE_DIR=${RELEASE_DIR} REGISTRY=${{ env.PROD_REGISTRY }} ORG=${{ env.PROD_ORG }} make release

  notify-failure:
    name: Notify failure in Slack
    needs: [release]
    if: ${{ failure() || cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v2.1.1
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Rancher turtles RELEASE test failed."
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github:",
                          "emoji": true
                        },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

  clean-up:
    name: Release testing clean up
    needs: [release]
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Delete nightly tag (local only)
        run: |
          git tag -d ${{ env.RELEASE_TAG }} || true
